language: node_js
node_js:
  - 10.10.0
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "lqGqit7/icvwRDgNMC2Qpxpl+Lx5YZMaI7oi5DZWL2Kc5uHOWCGv44Drf/yk21cM4kl6ug1edyN6NHhahXWVD7vSqdfubaQqNZ7XImvfhaj7EhX1x+8q1uQKj4dmE7HEKobpMew8D1ysw4Khgd9S1NeR0voFZHlUZNAAsLrxia7OAdu/d1bJ49l3q04bT3oeFW/jYVUghMWxzFsArsIodDn28rF6lPN43jswojSHsaEOQ/cZI4PzaS9U5nODTiPYz6pWIshrghjdfCssZ+3OZRINDlFeKihp1t1O6OLsqOyQpuSlUKHntiQD6LGOCrgIlIA1L66+DxlOatjB/xYSev0TwPvK28F+2aUvIKu+/F3lMshCuZo9SSmQVitK4+kG/bi5Ai6HTYkXvtEHYHyCIicK3xYQwh27aYsdPR3GipR3tR4cHDSN8ZxbMTdSsGcbnEy7DAEQsgJb8f68VAVgwPRL7tQWFvDSStMrkCbO3p22sBX4xK52Tkw+b0g7sAn/TlBBor8ggiJ6PLphK7uvTeIPlprmieujidKEmcDcylfz/o6dexTi4wto+veBcfLvCfbLBGuPfx0McGCE+lyKDlYpIoj9WjrlyWyZfgFROfbyPM19fk8rJOz07OzE58Ii5T/04S7BgpvicSTUQVhJGuHQ+sqqjm3iZqtIe29J3k8="
  app:
    master: whynohoursserver 